SufficientlySecure/document-viewer

- document-viewer/jni/ebookdroid/mupdfdroidbridge.c
ttOutline() (in org.ebookdroid.droids.mupdf.codec.MuPdfOutline)
fails to find any outline if the argument `outline` is negative.
The JNI part of org.ebookdroid.droids.mupdf.codec.MuPdfOutline had
the following code:
return (jlong) (long) doc->outline;
But this returns negative value if the most significant bit
of outline handle is 1, because `sizeof long` is 4 (32 bit)
and outline handler itself is a 32-bit pointer.
> Fix: no outline found with PDFs

- build.gradle
- document-viewer/build.gradle
This PR introduces splitting apk for each ABIs (which is suggessted in #88).
This needs newer SDK than v19 (I guess),
so I upgraded SDK and Gradle plugin as well.
It seems to me like upgrading SDK alone makes no bad side effects to UI (which is mentioned in #92).
> Split apk for each ABIs (and upgrade SDK to v22)

- document-viewer/jni/ebookdroid/mupdfdroidbridge.c
- document-viewer/src/main/java/org/ebookdroid/core/AbstractViewController.java
- document-viewer/src/main/java/org/ebookdroid/droids/mupdf/codec/MuPdfLinks.java
* Modify MuPdfLinks.fillPageLinkSourceRect() to fill in the link rect for any link type, not just FZ_LINK_GOTO
* Check link.url in AbstractViewController.processLinkTap(), added a goToUrl method to open the URL.
* In MuPdfLinks.getPageLinks(), always set link.rectType and link.sourceRect
With these changes, URL hyperlinks in PDF documents are highlighted in yellow and open in the browser when tapped.
> Support FZ_LINK_URI links in pdf documents.

- document-viewer/src/main/AndroidManifest.xml
PR #99 already upgraded build SDK in build.gradle,
but targetSdkVersion in AndroidManifest is still 19.
This PR fixes this situation.
> Upgrade targetSdkVersion in AndroidManifest.xml to 22

- document-viewer/build.gradle
Since one cannot upload split-ABI APKs with the same vercode, hence
assign each APK a different vercode.
Since the least significant digit in the vercode doesn't change between
releases (always 0), hence just change the least significant digit for
each ABI build.
> Assign a different vercode for each ABI build

- document-viewer/src/main/java/org/ebookdroid/core/AbstractViewController.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/IView.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/stubs/ViewStub.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/viewers/GLView.java
If you do a "fling" to scroll quickly, and then tap to stop scrolling, currently that tap will also be handled as its own action (e.g. if you tap a link, or in the bottom of the screen to trigger a flip to the next page, those events will happen.)
With this PR, a tap that stops a fling won't do anything else.
Normally this wouldn't be a very noticeable change, since tapping on the middle of a page doesn't do anything by default. However, if you configure a tap in the middle of the screen to toggle fullscreen, it's quite annoying when a tap to stop a fling also toggles fullscreen.
> Ignore taps that stop scrolling

- document-viewer/src/main/java/org/ebookdroid/common/bitmaps/GLBitmaps.java
- document-viewer/src/main/java/org/ebookdroid/common/touch/MultiTouchGestureDetector.java
- document-viewer/src/main/java/org/ebookdroid/common/touch/TouchManagerView.java
- document-viewer/src/main/java/org/ebookdroid/core/AbstractViewController.java
- document-viewer/src/main/java/org/ebookdroid/core/Page.java
- document-viewer/src/main/java/org/ebookdroid/core/curl/Vector2D.java
- document-viewer/src/main/java/org/emdev/common/textmarkup/TextStyle.java
- document-viewer/src/main/java/org/emdev/ui/gl/StringTexture.java
- document-viewer/src/main/java/org/emdev/utils/MathUtils.java
FloatMath was deprecated in API 22, and removed in API 23.
This is a prerequisite for upgrading the target SDK version to 23.
> Replace uses of FloatMath class with Math

- document-viewer/src/main/java/org/ebookdroid/core/AbstractViewController.java
AbstractViewController.dispatchKeyEvent(): If a key is bound, consume both key down and key up events.
Previously, this code was only consuming the key up events.
This fixes https://github.com/SufficientlySecure/document-viewer/issues/128  (tested on my Nexus 4 running Android 5.1.1); now the system volume control UI no longer appears when I use the volume buttons to flip pages.
TODO: For the scroll up/down keybindings, it would be better if the scrolling continued as long as you held the buttons down, instead of just scrolling once upon releasing the button.
> Fix for volume UI appearing when scrolling with volume buttons

- document-viewer/src/main/java/org/ebookdroid/ui/viewer/ViewerActivityController.java
- document-viewer/src/main/java/org/emdev/common/content/ContentScheme.java
https://github.com/SufficientlySecure/document-viewer/pull/140 introduced a bug where opening a pdf from the Gmail app causes a crash.
ViewerActivityController.afterCreate() requres that if `temporary` is false, the document URI is a file:// URI that can be converted to a filename, which PR140 broke.
Instead, I added a new ContentScheme.promptForSave field that's just used to decide whether to show a save dialog.
edit: So the main change here is making the "content" scheme temporary again like it was before #140 , but still hiding the save prompt for the content:// scheme.
> Fix a crash introduced by my recent change to ContentScheme

- init.sh
init.sh applies patches, so this makes it clear out the patches applied by a previous invocation of init.sh.
> init.sh: specify --force to "git submodule update" to discard local changes in submodules

- document-viewer/src/main/java/org/ebookdroid/CodecType.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/ViewerActivityController.java
- document-viewer/src/main/java/org/emdev/common/cache/CacheManager.java
- document-viewer/src/main/java/org/emdev/common/content/ContentScheme.java
Fixes https://github.com/SufficientlySecure/document-viewer/issues/149 (epub files not loading from the Downloads app.)
> Use correct extension for temporary files for content:// data

- document-viewer/src/main/java/org/ebookdroid/common/settings/AppSettings.java
- document-viewer/src/main/java/org/ebookdroid/common/settings/books/BookSettings.java
- document-viewer/src/main/java/org/ebookdroid/common/settings/definitions/AppPreferences.java
- document-viewer/src/main/java/org/ebookdroid/common/settings/types/RotationType.java
- document-viewer/src/main/java/org/ebookdroid/ui/settings/BookSettingsActivity.java
- document-viewer/src/main/java/org/ebookdroid/ui/settings/SettingsActivity.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/ViewerActivityController.java
- document-viewer/src/main/res/values/service_preferences_render.xml
- document-viewer/src/main/res/values/strings_preferences_render.xml
- document-viewer/src/main/res/xml-v10/fragment_render.xml
- document-viewer/src/main/res/xml-v14/fragment_render.xml
- document-viewer/src/main/res/xml/fragment_render.xml
It's still present as a book setting, with the same options (unspecified, portrait, landscape) as before, and the toolbar buttons still work as expected.
> Remove rotation from app settings.

- document-viewer/src/main/java/org/ebookdroid/EBookDroidApp.java
- document-viewer/src/main/java/org/ebookdroid/ui/library/RecentActivityController.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/ViewerActivityController.java
AFAIK this is considered bad practice on Android - it's supposed to be left up to the OS, and it slows down app startup because the process has to be started from scratch.
> Don't call System.exit(0) when last activity closes

- document-viewer/src/main/java/org/ebookdroid/ui/library/BrowserActivity.java
- document-viewer/src/main/java/org/ebookdroid/ui/library/BrowserActivityController.java
- document-viewer/src/main/java/org/ebookdroid/ui/library/RecentActivity.java
- document-viewer/src/main/java/org/ebookdroid/ui/opds/OPDSActivity.java
Fixes https://github.com/SufficientlySecure/document-viewer/issues/124
Also, makes the file browser and OPDS activity close on keyUp (rather than keyDown, as before) of the Back button.
> Fix for closing the file browser or OPDS activity also closing the Library

- document-viewer/src/main/java/org/ebookdroid/core/AbstractViewController.java
Key repeats when holding the volume up/down keys (to trigger scrolling) were broken in e7432ad.
Fixes https://github.com/SufficientlySecure/document-viewer/issues/164
> Fix continuous scrolling when holding volume up/down buttons

- document-viewer/src/main/AndroidManifest.xml
- document-viewer/src/main/java/org/ebookdroid/common/provider/DocumentContentProvider.java
- document-viewer/src/main/java/org/ebookdroid/ui/viewer/ViewerActivityController.java
- document-viewer/src/main/res/menu-sw600dp-v11/mainmenu.xml
- document-viewer/src/main/res/menu-v11/mainmenu.xml
- document-viewer/src/main/res/menu/mainmenu.xml
- document-viewer/src/main/res/menu/mainmenu_context.xml
- document-viewer/src/main/res/values/strings_mainmenu.xml
This is @fid-jose 's pull request https://github.com/SufficientlySecure/document-viewer/pull/170 , plus some changes I made:
- fixed security issue by making content provider non-exported
- add a "Open with..." menu item, which is like Share but uses ACTION_VIEW. This gives me the option to open documents with other PDF viewers, whereas "Share" (ACTION_SEND) just has things like dropbox, gmail, etc.
> Add "Share" and "Open with..." menu items

- document-viewer/src/main/java/org/ebookdroid/EBookDroidApp.java
- document-viewer/src/main/java/org/emdev/ui/gl/BaseEGLConfigChooser.java
- document-viewer/src/main/java/org/emdev/ui/gl/GLConfiguration.java
Previously, we were requesting 1 on non-emulators, and 0 on emulators, because emulators use Android's software GLES implementation that doesn't support stencil.
That meant the app wouldn't run on devices without stencil support.
This should fix https://github.com/SufficientlySecure/document-viewer/issues/94
> GLES configuration: fall back to EGL_STENCIL_SIZE 0, if 1 is not available

- document-viewer/src/main/java/org/ebookdroid/core/DecodeServiceBase.java
as discussed here: https://github.com/SufficientlySecure/document-viewer/issues/89
I thought I would make a pr for this. I'll keep testing it.
Agree in general we don't want to make changes without understanding the code.
The bug this fixes is pretty annoying though.
> DecodeServiceBase.calculateRootCropping(): remove goToPage call

- document-viewer/jni/ebookdroid/mupdfdroidbridge.c
- document-viewer/jni/mupdf/Core.mk
- document-viewer/jni/mupdf/ThirdParty.mk
- document-viewer/jni/mupdf/overrides/nightmode_slowcmyk.patch
- init.sh
- Disabled overrides/fonts.patch because it no longer applies cleanly due to refactoring in mupdf
- Core.mk and ThirdParty.mk update from mupdf repository. Paths tweaked to build in our repository, and restored the -DNOCJK flag we were using. Also added -DTOFU which disables more fonts that were added since mupdf 1.7.
Question: should the fonts.patch be restored?
I'm not sure what the original purpose of the patch was.
- If the idea is to substitute fonts in EPUB documents, we should see if there is a proper API in mupdf for this rather than maintaining this hacky patch.
- If the idea was to substitute fonts in PDF documents, this is wrong, afaik. Unless the idea was to compile mupdf without the PDF core fonts to save space, and then provide them from the DV font pack? Anyway, that seems …
> Update mupdf to 1.9a

- document-viewer/jni/djvu/Android.mk
- document-viewer/jni/mupdf/Core.mk
- document-viewer/jni/mupdf/ThirdParty.mk
Fixes #244.
This is simply an update of mupdf,
dosen't include changes (on our application side) for loading system fonts.
> Update mupdf to v1.11

- document-viewer/src/main/res/values/service_preferences_performance.xml
Crash resolved by making the default (performance -> pages in memory) setting anything larger than 0 (minimum=1 and default=4)
See:
https://github.com/SufficientlySecure/document-viewer/issues/299#issuecomment-512682996
https://github.com/SufficientlySecure/document-viewer/issues/302#issuecomment-512650844
> Fix Android 8 and above crash

- document-viewer/src/main/java/org/emdev/ui/uimanager/UIManager44x.java
Hey, after years! The only annoying thing for me now on a tablet, originally copied it from UIManager41x.java but it is really not needed I can say in a 10' or 7' tablet so lets always enable immersive mode no matter tablet or not. Thanks!
> Fix immersive mode for tablet

- document-viewer/src/main/res/values-es/strings_actions.xml
- document-viewer/src/main/res/values-es/strings_bookmenu.xml
- document-viewer/src/main/res/values-es/strings_common.xml
- document-viewer/src/main/res/values-es/strings_mainmenu.xml
- document-viewer/src/main/res/values-es/strings_manual_cropping.xml
- document-viewer/src/main/res/values-es/strings_opdsmenu.xml
- document-viewer/src/main/res/values-es/strings_preferences_backup.xml
- document-viewer/src/main/res/values-es/strings_preferences_browser.xml
- document-viewer/src/main/res/values-es/strings_preferences_navigation.xml
- document-viewer/src/main/res/values-es/strings_preferences_opds.xml
- document-viewer/src/main/res/values-es/strings_preferences_performance.xml
- document-viewer/src/main/res/values-es/strings_preferences_render.xml
- document-viewer/src/main/res/values-es/strings_preferences_scroll.xml
- document-viewer/src/main/res/values-es/strings_preferences_typespec.xml
- document-viewer/src/main/res/values-es/strings_preferences_ui.xml
Update and complete Spanish translation.
I have added \n where appropiate so the layout of the Spanish file matches the English one and then it's easier to see diffs. I've also removed quotes (") where they were not needed, and fixed ending <string> changing them to </string>. I've reviewed the translated strings and added the pending ones.
> Update and complete Spanish translation
